export default {
	dark: {
		'--fracgui-root-width': '30rem',
		'--fracgui-root-min-width': '25rem',
		'--fracgui-root-max-width': '35rem',
		'--fracgui-root-header-font-family': "'fredoka', sans-serif",
		'--fracgui-root-header-font-size': 'var(--font-xs)',
		'--fracgui-root-header-font-weight': '500',
		'--fracgui-root-header-height': '1.75rem',
		'--fracgui-root-header-letter-spacing': '0.125rem',
		'--fracgui-root-alpha': '0.75',
		'--fracgui-root-blur': '0.5rem',
		'--fracgui-folder-background': 'rgba(var(--bg-b-rgb), 0.5)',
		'--fracgui-folder-header-padding-left': '0.25rem',
		'--fracgui-folder-header-color': 'var(--fg-c)',
		'--fracgui-folder-header-dim-color': 'var(--fg-d)',
		'--fracgui-folder-header-background': 'var(--bg-a)',
		'--fracgui-folder-header-outline': 'none',
		'--fracgui-folder-header-box-shadow': 'none',
		'--fracgui-folder-header-font-size': 'var(--font-sm)',
		'--fracgui-folder-header-font-weight': '350',
		'--fracgui-folder-header-letter-spacing': '0.75px',
		'--fracgui-folder-content-background': 'rgba(var(--bg-b-rgb), 0.2)',
		'--fracgui-folder-content-padding-left': '0.33rem',
		'--fracgui-folder-content-font-size': 'var(--font-xs)',
		'--fracgui-folder-content-font-weight': '350',
		'--fracgui-folder-content-letter-spacing': '0.5px',
		'--fracgui-toolbar-icon-dim-color': 'var(--bg-c)',
		'--fracgui-toolbar-icon-color': 'var(--bg-d)',
		'--fracgui-input-height': '2rem',
		'--fracgui-input-shadow': 'var(--shadow-xs)',
		'--fracgui-input-outline': '1px solid rgba(var(--bg-d-rgb), 0.4)',
		'--fracgui-input-section-1-width': 'clamp(6rem, 30%, 12rem)',
		'--fracgui-input-section-2-width': '4rem',
		'--fracgui-input-section-3-width': '100%',
		'--fracgui-input-container-color': 'var(--fg-d)',
		'--fracgui-input-container-dim-color': 'var(--fg-e)',
		'--fracgui-input-container-background': 'rgba(var(--bg-a-rgb), 0.5)',
		'--fracgui-input-container-outline': '1px solid rgba(var(--bg-a-rgb), 0.2)',
		'--fracgui-input-container-box-shadow':
			'-0.15px 0.1px 1px hsla(220, 10%, 2%, calc(0.2 * var(--shadow-alpha))) inset, -2px 2px 15px hsla(220, 10%, 2%, calc(0.075 * var(--shadow-alpha))) inset, -3.0px 3px 25px hsla(220, 10%, 2%, calc(0.05 * var(--shadow-alpha))) inset, -10.0px 10px 50px hsla(220, 10%, 2%, calc(0.025 * var(--shadow-alpha))) inset',
		'--fracgui-input-content-box-shadow': 'var(--shadow-xs)',
		'--fracgui-controller-outline': '1px solid rgba(var(--bg-d-rgb), 0.4)',
		'--fracgui-input-font-size': 'var(--font-xs)',
		'--fracgui-input-number-range-color': 'var(--bg-c)',
		'--fracgui-input-number-range-active-color': 'var(--theme-a)',
		'--fracgui-input-number-range-background': 'var(--bg-a)',
		'--fracgui-input-number-range-outline': '1px solid rgba(var(--bg-c-rgb), 0.25)',
		'--fracgui-input-number-range-shadow':
			'-2px 2px 2.5px hsla(230, 20%, 0%, 0.2), 2px 2px 5px hsla(230, 20%, 0%, 0.2), 2px 3px 10px hsla(230, 20%, 0%, 0.2), 2px 4px 4px hsla(230, 25%, 0%, 0.2)',
	},
	light: {
		'--fracgui-controller-dim-background': 'rgba(var(--bg-a-rgb), 0.5)',
		'--fracgui-controller-background': 'rgba(var(--bg-a-rgb), 1)',
		'--fracgui-controller-color': 'var(--fg-a)',
		'--fracgui-controller-dim-color': 'var(--fg-c)',
		'--fracgui-input-outline': '1px solid rgba(var(--bg-d-rgb), 0.1)',
		'--fracgui-input-number-range-background': 'var(--bg-b)',
		'--fracgui-input-number-range-color': 'var(--bg-d)',
		'--fracgui-input-number-range-shadow':
			'-2px 2px 2px hsla(230, 20%, 30%, 0.1), 2px 2px 3px hsla(230, 20%, 30%, 0.1), 2px 2px 7px hsla(230, 20%, 30%, 0.1)',
	},
}
